server:
  port: 8484
spring:
  application:
    name: zuul
  redis:
    database: 0
    host: 112.74.52.200
    port: 2379
    password: Lywx3403
    timeout: 2000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#zuul:
#  routes:
#    users:
#      path: /test/**
#      url: http://localhost:9999/test/
zuul:
  routes:
    teasegame:
      path: /test/**
      serviceId: tease-game
    game:
      path: /game/**
      serviceId: game
  strip-prefix: false
#zuul:
#  routes:
#    tease-game:
#        path: /test/**
#        serviceId: TEASE-GAME
#    baidu:
#        path: /second/**
#        url: forward:http://cloud.spring.io/spring-cloud-static/Finchley.RC1/single/spring-cloud.html#netflix-zuul-starter
#    third:
#        path: /third/**
#        url: forward:/3rd
#    users:
#      path: /test/**
#      serviceId: TEASE-GAME
